config/routes.rb
Rails.application.routes.draw do
  root 'leads#index'
  resources :lists do
    collection { patch 'bulk_update' }
  end
  resources :leads
  resources :list_leads
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lead.rb
class Lead < ApplicationRecord
    has_many :list_leads, dependent: :destroy
    has_many :lists, through: :list_leads
end

app/models/list.rb
class List < ApplicationRecord
  has_many :list_leads, dependent: :destroy
  has_many :leads, through: :list_leads
end

app/models/list_lead.rb
class ListLead < ApplicationRecord
  belongs_to :list
  belongs_to :lead
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[show edit update destroy]

  # GET /leads or /leads.json
  def index
    @q = Lead.ransack(params[:q])
    @leads = @q.result
    @pagy, @leads = pagy(@leads)
  end

  # GET /leads/1 or /leads/1.json
  def show; end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit; end

  # POST /leads or /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html do
          redirect_to lead_url(@lead), notice: 'Lead was successfully created.'
        end
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html do
          redirect_to lead_url(@lead), notice: 'Lead was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy

    respond_to do |format|
      format.html do
        redirect_to leads_url, notice: 'Lead was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lead
    @lead = Lead.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lead_params
    params.require(:lead).permit(:first_name, :last_name, :email)
  end
end

app/controllers/list_leads_controller.rb
class ListLeadsController < ApplicationController
  before_action :set_list, only: %i[create ]

  def create
    @list.lead_ids = [@list.lead_ids + params[:ids].map(&:to_i)].flatten.uniq
    redirect_to list_path(@list)
  end
  
  private

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  # GET /lists or /lists.json
  def index
    @q = List.ransack(params[:q])
    @lists = @q.result
    @pagy, @lists = pagy(@lists)
  end

  # GET /lists/1 or /lists/1.json
  def show
    @q = @list.leads.ransack(params[:q])
    @leads = @q.result
    @pagy, @leads = pagy(@leads)
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit; end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html do
          redirect_to list_url(@list), notice: 'List was successfully created.'
        end
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html do
          redirect_to list_url(@list), notice: 'List was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def bulk_update
    @list = List.find(params[:list_id])
    @leads = Lead.find(params[:ids])
    @leads.each { |lead| ListLead.destroy_by(list: @list, lead: lead) }
    flash[:confetti] = 'List was successfully updated.'
    redirect_to list_path(@list)
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html do
        redirect_to lists_url, notice: 'List was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_list
    @list = List.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/headers/_navbar.html.erb
<nav>
  <%= link_to "Leads", leads_path %>
  <%= link_to "Lists", lists_path %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TablePractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.4.0/dist/confetti.browser.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'headers/navbar' %>
    <turbo-frame id="flash">
      <%= render 'shared/flash' %>
    </turbo-frame>
    <%= yield %>
  </body>
</html>

app/views/leads/_form.html.erb
<%= form_with(model: lead) do |form| %>
  <% if lead.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
        <% lead.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/leads/_lead.html.erb
<div class="card" id="<%= dom_id lead %>">
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= lead.name %>
  </p>
  <p>
    <strong>Gender:</strong>
    <%= lead.gender %>
  </p>
  <p>
    <strong>Hobby:</strong>
    <%= lead.hobby %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= lead.email %>
  </p>
</div>

</div>

app/views/leads/_table.html.erb
<table>
  <div>
    <%= check_box_tag nil, nil, false, data: { bulk_select_target: "checkboxAll" } %>
    <label>
      Select All
    </label>
  </div>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Select</th>
      <th scope="col">
        <%= sort_link(q, :name) do %>
          Name
        <% end %>
      </th>
      <th scope="col">
        <%= sort_link(q, :email) do %>
          Email
        <% end %>
      </th>
      <th scope="col">
        <%= sort_link(q, :gender) do %>
          Gender
        <% end %>
      </th>
      <th scope="col">
        <%= sort_link(q, :hobby) do %>
          Hobby
        <% end %>
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% leads.each_with_index do |lead, index| %>
      <%= render 'leads/tr', { lead: lead, index: index } %>
    <% end %>
  </tbody>
</table>

app/views/leads/_tr.html.erb
<tr scope="row">
  <td>
    <%= index += 1 %>
  </td>
  <td>
    <div class="form-check">
      <%= check_box_tag "ids[]", lead.id, false, data: { bulk_select_target: "checkbox" } %>
      <label class="form-check-label"></label>
    </div>
  </td>
  <td>
    <%= link_to lead_path(lead), style: "text-decoration: none" do %>
      <%= lead.name.humanize %>
    <% end %>
  </td>
  <td><%= lead.email %></td>
  <td><%= lead.gender %></td>
  <td><%= lead.hobby %></td>
  <td>
    <%= link_to "Edit", edit_lead_path(lead) %>
  </td>
  <td>
    <%= link_to "Show", lead_path(lead) %>
  </td>
  <td>
    <%= button_to "Destroy", lead, method: :delete %>
  </td>
</tr>

app/views/leads/edit.html.erb
<h1>Editing lead</h1>

<%= render "form", lead: @lead %>

<br>

<div>
  <%= link_to "Show this lead", @lead %> |
  <%= link_to "Back to leads", leads_path %>
</div>

app/views/leads/index.html.erb
<h1>Leads</h1>
<div class="table-container">
  <%== pagy_nav(@pagy) %>
  <div
    data-controller="bulk-select"
    data-bulk-select-url-value="<%= list_leads_url %>"
  >
    <div class="flex-group">
      <div class="input-group">
        <%= link_to "Add to List", "#", data: { action: "click->bulk-select#addToList" } %>
        <select class="form-select" aria-label="available lists">
          <% List.all.reverse.each do |list| %>
            <option data-bulk-select-target="id" value="<%= list.id %>">
              <%= list.title %>
            </option>
          <% end %>
        </select>
      </div>
      <%= search_form_for @q, url: leads_path, class: "input-group" do |f| %>
        <%= f.label :name_or_gender_or_email_or_hobby_cont, "Email/Name" %>
        <%= f.search_field :name_or_gender_or_email_or_hobby_cont %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
    <%= render "table", { q: @q, leads: @leads } %>
  </div>
</div>

app/views/leads/new.html.erb
<h1>New lead</h1>

<%= render "form", lead: @lead %>

<br>

<div>
  <%= link_to "Back to leads", leads_path %>
</div>

app/views/leads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lead %>

<div>
  <%= link_to "Edit this lead", edit_lead_path(@lead) %> |
  <%= link_to "Back to leads", leads_path %>

  <%= button_to "Destroy this lead", @lead, method: :delete %>
</div>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Title:</strong>
    <%= list.title %>
  </p>

</div>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="flex-group" >
  <h1>Lists</h1>
  <%= search_form_for @q, url: lists_path, class:"list-search" do |f| %>
    <%= f.label :title_cont, "Title Search" %>
    <%= f.search_field :title_cont %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>
<%= link_to "New list", new_list_path %>
<div id="lists">
  <% @lists.each do |list| %>
    <div class="card">
      <%= render list %>
    </div>
    <p>
      <%= link_to "Show this list", list %>
    </p>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<h1>List: <%= @list.title%> </h1>
<div class="table-container" >
  <%== pagy_nav(@pagy) %>
  <div
    data-controller="bulk-select"
    data-bulk-select-url-value="<%= bulk_update_lists_path %>"
  >
    <option data-bulk-select-target="id" selected value="<%= @list.id %>" style="display: none"></option>
    <div class="flex-group">
      <div class="input-group">
        <%= link_to "Remove from List", "#", data: { action: "click->bulk-select#removeFromList" } %>
      </div>
      <%= search_form_for @q, url: leads_path, class: "input-group" do |f| %>
        <%= f.label :name_or_gender_or_email_or_hobby_cont, "Email/Name" %>
        <%= f.search_field :name_or_gender_or_email_or_hobby_cont %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
    <%= render "leads/table", { q: @q, leads: @leads } %>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="flash-messages">
  <% flash.each do |type, message| %>
    <div class="flash-message" data-controller="confetti">
      <p style="color: green"><%= message %></p>
    </div>
  <% end %>
</div>